version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: sudo npm install -g @angular/cli
      - run: ng build --configuration production
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: /workspace
      - run: |
          npm install -g angular-cli
          ng serve --host 0.0.0.0 --port 80 --disableHostCheck true

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
